
target 'BikeShare' do
    pod 'common', :path => '../../common'
    pod "SwiftUIRefresh"
    pod 'KMPNativeCoroutinesAsync'
end


target 'BikeShareWidgetExtension' do
    pod 'common', :path => '../../common'
    pod 'KMPNativeCoroutinesAsync'
end